import getConfig from 'next/config';

const { publicRuntimeConfig } = getConfig();
const {
  NEXT_PUBLIC_GRPC_URL,
  NEXT_PUBLIC_GREENFIELD_RPC_URL,
  NEXT_PUBLIC_GREEN_CHAIN_ID,
  NEXT_PUBLIC_BSC_RPC_URL,
  NEXT_PUBLIC_BSC_CHAIN_ID,
  NEXT_PUBLIC_TOKEN_HUB_CONTRACT_ADDRESS,
  NEXT_PUBLIC_CROSS_CHAIN_CONTRACT_ADDRESS,
  NEXT_PUBLIC_ACCOUNT_ADDRESS,
  NEXT_PUBLIC_ACCOUNT_PRIVATEKEY,
} = publicRuntimeConfig || {};

export const GRPC_URL = NEXT_PUBLIC_GRPC_URL;
export const GREENFIELD_RPC_URL = NEXT_PUBLIC_GREENFIELD_RPC_URL;
export const GREEN_CHAIN_ID = parseInt(NEXT_PUBLIC_GREEN_CHAIN_ID);
export const BSC_RPC_URL = NEXT_PUBLIC_BSC_RPC_URL;
export const BSC_CHAIN_ID = parseInt(NEXT_PUBLIC_BSC_CHAIN_ID);
export const TOKEN_HUB_CONTRACT_ADDRESS = NEXT_PUBLIC_TOKEN_HUB_CONTRACT_ADDRESS;
export const CROSS_CHAIN_CONTRACT_ADDRESS = NEXT_PUBLIC_CROSS_CHAIN_CONTRACT_ADDRESS;
export const ACCOUNT_ADDRESS = NEXT_PUBLIC_ACCOUNT_ADDRESS;
export const ACCOUNT_PRIVATEKEY = NEXT_PUBLIC_ACCOUNT_PRIVATEKEY;
