import getConfig from 'next/config';

const { publicRuntimeConfig } = getConfig();
const {
  NEXT_PUBLIC_GRPC_URL,
  NEXT_PUBLIC_GREENFIELD_RPC_URL,
  NEXT_PUBLIC_GREEN_CHAIN_ID,
  NEXT_PUBLIC_BSC_RPC_URL,
  NEXT_PUBLIC_BSC_CHAIN_ID,
  NEXT_PUBLIC_TOKEN_HUB_CONTRACT_ADDRESS,
  NEXT_PUBLIC_CROSS_CHAIN_CONTRACT_ADDRESS,
  NEXT_PUBLIC_ACCOUNT_ADDRESS,
  NEXT_PUBLIC_ACCOUNT_PRIVATEKEY,
  NEXT_PUBLIC_VALIDATOR_PRIVATEKEY,
  NEXT_PUBLIC_EXECUTOR_ADDRESS,
  NEXT_PUBLIC_CROSSCHAIN_ADDRESS,
  NEXT_PUBLIC_MULTIMESSAGE_ADDRESS,
  NEXT_PUBLIC_BUCKETHUB_ADDRESS,
  NEXT_PUBLIC_OBJECTHUB_ADDRESS,
  NEXT_PUBLIC_TOKENHUB_ADDRESS,
  NEXT_PUBLIC_PERMISSIONHUB_ADDRESS,
  NEXT_PUBLIC_GROUPHUB_ADDRESS,
} = publicRuntimeConfig || {};

export const GRPC_URL = NEXT_PUBLIC_GRPC_URL;
export const GREENFIELD_RPC_URL = NEXT_PUBLIC_GREENFIELD_RPC_URL;
export const GREEN_CHAIN_ID = parseInt(NEXT_PUBLIC_GREEN_CHAIN_ID);
export const BSC_RPC_URL = NEXT_PUBLIC_BSC_RPC_URL;
export const BSC_CHAIN_ID = parseInt(NEXT_PUBLIC_BSC_CHAIN_ID);
export const TOKEN_HUB_CONTRACT_ADDRESS = NEXT_PUBLIC_TOKEN_HUB_CONTRACT_ADDRESS;
export const CROSS_CHAIN_CONTRACT_ADDRESS = NEXT_PUBLIC_CROSS_CHAIN_CONTRACT_ADDRESS;
export const ACCOUNT_ADDRESS = NEXT_PUBLIC_ACCOUNT_ADDRESS;
export const ACCOUNT_PRIVATEKEY = NEXT_PUBLIC_ACCOUNT_PRIVATEKEY;
export const VALIDATOR_PRIVATEKEY = NEXT_PUBLIC_VALIDATOR_PRIVATEKEY;

export const EXECUTOR_ADDRESS = NEXT_PUBLIC_EXECUTOR_ADDRESS;
export const CROSSCHAIN_ADDRESS = NEXT_PUBLIC_CROSSCHAIN_ADDRESS;
export const MULTIMESSAGE_ADDRESS = NEXT_PUBLIC_MULTIMESSAGE_ADDRESS;
export const BUCKETHUB_ADDRESS = NEXT_PUBLIC_BUCKETHUB_ADDRESS;
export const OBJECTHUB_ADDRESS = NEXT_PUBLIC_OBJECTHUB_ADDRESS;
export const TOKENHUB_ADDRESS = NEXT_PUBLIC_TOKENHUB_ADDRESS;
export const PERMISSIONHUB_ADDRESS = NEXT_PUBLIC_PERMISSIONHUB_ADDRESS;
export const GROUPHUB_ADDRESS = NEXT_PUBLIC_GROUPHUB_ADDRESS;
