import { Demo } from '@/components/demo';
import { Wallet } from '@/components/wallet';
import { useIsMounted } from '@/hooks/useIsMounted';
import styles from '@/styles/Home.module.css';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { useAccount } from 'wagmi';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const isMounted = useIsMounted();
  const { isConnected } = useAccount();

  if (!isMounted) return null;

  return (
    <>
      <Head>
        <title>Create Greenfield App</title>
        <meta name="description" content="Generated by create Greenfield app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Wallet />
        {isConnected && (
          <>
            <Demo />
          </>
        )}
      </main>
    </>
  );
}
